import './globals.css'

export const metadata = {
  title: 'Coinbase Recovery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-full min-h-screen'>{children}</body>
    </html>
  )
}
